### ISSUE TITLE
Lambda trigger question

### ISSUE THREAD

**Issue by unbalanced** [mParticle/mparticle-firehose-java-sdk#2]
Hey guys
I'm trying to figure the Firehose integration.
Usually a lambda function is triggered by an AWS event (sqs message, s3, kinesis, etc..)
What is the trigger in the mParticle integration?

Thanks

**Comment by akatz0813** [comment]
Hi @unbalanced. In this case, mParticle will call the lambda function directly. There will not be any trigger configured. We provide test json that you can use to test your function.
