### ISSUE TITLE
SDK deserializer unable to deserialize example into TextSetting

### ISSUE THREAD

**Issue by travisemichael** [mParticle/mparticle-firehose-java-sdk#5]
Using the example EventProcessingRequest json located [here](https://github.com/mParticle/mparticle-firehose-java-sdk/blob/master/examples/json/EventProcessingRequest_android.json) to test our implementation.

We are using com.mparticle:java-sdk:2.2.0 and are unable deserialize into a com.mparticle.sdk.model.Message. We get the following error message from the parser:

> Can not construct instance of com.mparticle.sdk.model.registration.TextSetting: no suitable constructor found, can not deserialize from Object value (missing default constructor or creator, or perhaps need to add/enable type information?)

After removing the TextSetting from the list on the request json, the request parses normally.

**Comment by keananf** [comment]
Thanks for raising this! 
I can confirm this is no longer an issue as of the newest version of the SDK: `2.3.0`.
